### ISSUE TITLE
ModuleNotFoundError: No module named 'utility'

### ISSUE THREAD

**Issue by lalenzos** [stanford-futuredata/ColBERT#101]
Hi,
I wanted to use your model in my python project and added it therefore to my project (virtual pip env) by using the following command:
```
pip install git+https://github.com/stanford-futuredata/ColBERT
```

However, when I start my python project and wanted to use your demo code from the demo notebook, I'm always getting the following error:
```
Traceback (most recent call last):
  File "C:\backend\webservice.py", line 8, in <module>
    from controllers.colbert_controller import ColBertController
  File "C:\backend\controllers\colbert_controller.py", line 3, in <module>
    from colbert.infra import Run, RunConfig, ColBERTConfig
  File "C:\backend\venv\lib\site-packages\colbert\__init__.py", line 1, in <module>
    from .trainer import Trainer
  File "C:\backend\venv\lib\site-packages\colbert\trainer.py", line 1, in <module>
    from colbert.infra.run import Run
  File "C:\backend\venv\lib\site-packages\colbert\infra\__init__.py", line 1, in <module>
    from .run import *
  File "C:\backend\venv\lib\site-packages\colbert\infra\run.py", line 7, in <module>
    from colbert.infra.config import RunConfig
  File "C:\backend\venv\lib\site-packages\colbert\infra\config\__init__.py", line 1, in <module>
    from .config import *
  File "C:\backend\venv\lib\site-packages\colbert\infra\config\config.py", line 3, in <module>
    from .base_config import BaseConfig
  File "C:\backend\venv\lib\site-packages\colbert\infra\config\base_config.py", line 11, in <module>
    from utility.utils.save_metadata import get_metadata_only
ModuleNotFoundError: No module named 'utility'
```

Any idea how to solve this error? Thanks.

**Comment by okhat** [comment]
We're planning to make improvements to how the package works with pip.

In the meanwhile, please follow the import approach shown at the top of the intro notebook: https://github.com/stanford-futuredata/ColBERT/blob/new_api/docs/intro.ipynb

(Also, don't pip install the git repo. Instead, follow the installation instructions on the README of the branch you're using. We recommend conda.)

**Comment by luffycodes** [comment]
i used python ../setup.py install, and i get the same error !

**Comment by okhat** [comment]
@luffycodes Please follow in the instructions on the README for installation. Don't use the setup script directly.

**Comment by luffycodes** [comment]
conda env create -f conda_env.yml
conda activate colbert-v0.2

are these the commands to install colbert?

**Comment by okhat** [comment]
@luffycodes Which branch do you want to install?

**Comment by luffycodes** [comment]
I was interested in training v2 from scratch ! I think it is addressed in the other issue :)

Thanks a lot for the help and prompt reply :)

**Comment by okhat** [comment]
Thanks, @luffycodes ! Let me know if the commands for installation on the new_api branch and the corresponding ColBERTv2 notebook don't work for you.
