### ISSUE TITLE
UnboundLocalError: local variable 'batch_idx' referenced before assignment

### ISSUE THREAD

**Issue by ebritoc** [stanford-futuredata/ColBERT#118]
I am trying to train a ColBERT model on a new dataset based on the code snippet from the README.  I get stuck here:

```
#> Starting...
nranks = 2 	 num_gpus = 2 	 device=0
#> Starting...
nranks = 2 	 num_gpus = 2 	 device=1
Using config.bsize = 16 (per process) and config.accumsteps = 1
{
    "ncells": null,
    "centroid_score_threshold": null,
    "ndocs": null,
    "index_path": null,
    "nbits": 1,
    "kmeans_niters": 4,
    "resume": false,
    "similarity": "cosine",
    "bsize": 32,
    "accumsteps": 1,
    "lr": 3e-6,
    "maxsteps": 500000,
    "save_every": null,
    "warmup": null,
    "warmup_bert": null,
    "relu": false,
    "nway": 2,
    "use_ib_negatives": false,
    "reranker": false,
...
[Jul 18, 19:30:32] #> Got 98380 queries. All QIDs are unique.

[Jul 18, 19:30:32] #> Got 98380 queries. All QIDs are unique.

Some weights of HF_ColBERT were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['linear.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of HF_ColBERT were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['linear.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[Jul 18, 19:30:42] #> Done with all triples!
Process Process-3:
Traceback (most recent call last):
  File "/home/IAIS/ebritochac/anaconda3/envs/colbert/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/IAIS/ebritochac/anaconda3/envs/colbert/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "../colbert/infra/launcher.py", line 115, in setup_new_process
    return_val = callee(config, *args)
  File "../colbert/training/training.py", line 146, in train
    ckpt_path = manage_checkpoints(config, colbert, optimizer, batch_idx+1, savepath=None, consumed_all_triples=True)
UnboundLocalError: local variable 'batch_idx' referenced before assignment
```

**Comment by santhnm2** [comment]
Hi @ebritoc, it seems the main training loop is not being executed for some reason - it's possible that there is some data missing that is preventing the data loader from generating batches correctly. Could you paste your full call to `Trainer.train` with the corresponding `ColBERTConfig`?

**Comment by ebritoc** [comment]
```
if __name__=='__main__':
    with Run().context(RunConfig(nranks=2, experiment="gerdalir")):

        config = ColBERTConfig(
            bsize=32,
            root="../experiments",
        )
        trainer = Trainer(
            triples=triples,
            queries=queries,
            collection=collection,
            config=config,
        )        
        checkpoint_path = trainer.train()
```
Maybe there is is some issue with the triples since it is not clearly specified how the "JSONL triples file" should be generated. It is currently a JSONized list of lists of the form 
```
[[qid1, pid+1, pid-1],[qid2, pid+2, pid-2], ... ,[qidN, pid+N, pid-N]]
```

**Comment by ebritoc** [comment]
They do. I repeated the call with a minimal dataset consisting of:
collection.tsv:
```
0 text0
1 text1
```
queries.tsv:
```
0 text0
1 text1
```
triples,jsonl:
```
[[0,0,1],[1,1,0]]
```
I got exactly the same error.

**Comment by santhnm2** [comment]
Sorry for the delay in getting back to you, but I tried reproducing this on my end and I think the issue with the minimal example at least is that the LazyBatcher will immediately raise `StopIteration` if the total length of the triples is less than the specified batch size (which I assume you kept at 32 as per the example code snippet): https://github.com/stanford-futuredata/ColBERT/blob/main/colbert/training/lazy_batcher.py#L41
However, it seems your initial code was using 98380 queries in which case this wouldn't apply - would you be able to share the dataset and code that produced the initial error?

**Comment by ebritoc** [comment]
Now I'm the one apologizing for the late reaction 😅
You were right with the issue being triggered by the batch size. But now with a reduced batch size of 2, I get now the following error:

```
Process Process-1:
Traceback (most recent call last):
  File "/home/IAIS/ebritochac/anaconda3/envs/colbert/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/IAIS/ebritochac/anaconda3/envs/colbert/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/IAIS/ebritochac/methodigy/ColBERT/colbert/infra/launcher.py", line 115, in setup_new_process
    return_val = callee(config, *args)
  File "/home/IAIS/ebritochac/methodigy/ColBERT/colbert/training/training.py", line 87, in train
    for batch_idx, BatchSteps in zip(range(start_batch_idx, config.maxsteps), reader):
  File "/home/IAIS/ebritochac/methodigy/ColBERT/colbert/training/lazy_batcher.py", line 50, in __next__
    query = self.queries[query]
  File "/home/IAIS/ebritochac/methodigy/ColBERT/colbert/data/queries.py", line 73, in __getitem__
    return self.data[key]
TypeError: unhashable type: 'list'
```
This minimal dataset looks like this:
```
$ cat collection.test.tsv 
0       This is document 0.
1       This is document 1.
$ cat queries.test.tsv 
0       This is query 0.
1       This is query 1.
$ cat triples.test.jsonl 
[[0,0,1],[1,1,0]]
```

**Comment by santhnm2** [comment]
Ah could you try organizing your `triples.test.jsonl` as follows?
```
[0,0,1]
[1,1,0]
```

**Comment by ebritoc** [comment]
That solved the issue. Thank you!
