### ISSUE TITLE
ColBERTv2.0 indexer never returns

### ISSUE THREAD

**Issue by susavlsh10** [stanford-futuredata/ColBERT#139]
Hi, 

I have been trying to create the index using the scripts provided but it gets stuck after this:

![image](https://user-images.githubusercontent.com/54409828/199887112-f3f41e02-f1a2-43bb-9872-32e34ebb37b4.png)

I have been executing the following script: 

from colbert.infra import Run, RunConfig, ColBERTConfig
from colbert import Indexer

if __name__=='__main__':
    with Run().context(RunConfig(nranks=1, experiment="msmarco")):

        config = ColBERTConfig(
            nbits=2,
            root="/home/susavlsh10/kernels/ColBERT",
        )
        indexer = Indexer(checkpoint="/home/susavlsh10/kernels/ColBERT/colbertv2.0", config=config)
        indexer.index(name="msmarco.nbits=2", collection="/home/susavlsh10/kernels/ColBERT/colbertv2.0/collection.tsv", overwrite=True)
       

I cannot figure out why the code gets stuck. Any inputs would be appreciated.

**Comment by susavlsh10** [comment]
Furthermore, my GPU runs for 20-25 mins and the indexing plan gets saved. The following is saved in the plan:

{
    "config": {
        "ncells": null,
        "centroid_score_threshold": null,
        "ndocs": null,
        "index_path": null,
        "nbits": 2,
        "kmeans_niters": 20,
        "resume": false,
        "similarity": "cosine",
        "bsize": 64,
        "accumsteps": 1,
        "lr": 1e-5,
        "maxsteps": 400000,
        "save_every": null,
        "warmup": 20000,
        "warmup_bert": null,
        "relu": false,
        "nway": 64,
        "use_ib_negatives": true,
        "reranker": false,
        "distillation_alpha": 1.0,
        "ignore_scores": false,
        "query_maxlen": 32,
        "attend_to_mask_tokens": false,
        "interaction": "colbert",
        "dim": 128,
        "doc_maxlen": 180,
        "mask_punctuation": true,
        "checkpoint": "\/home\/susavlsh10\/kernels\/ColBERT\/colbertv2.0",
        "triples": "\/future\/u\/okhattab\/root\/unit\/experiments\/2021.10\/downstream.distillation.round2.2_score\/round2.nway6.cosine.ib\/examples.64.json",
        "collection": "\/home\/susavlsh10\/kernels\/ColBERT\/colbertv2.0\/collection.tsv",
        "queries": "\/future\/u\/okhattab\/data\/MSMARCO\/queries.train.tsv",
        "index_name": "msmarco.nbits=2",
        "overwrite": false,
        "root": "\/home\/susavlsh10\/kernels\/ColBERT\/experiments",
        "experiment": "msmarco",
        "index_root": null,
        "name": "2022-11\/03\/22.42.49",
        "rank": 0,
        "nranks": 1,
        "amp": true,
        "gpus": 1
    },
    "num_chunks": 354,
    "num_partitions": 262144,
    "num_embeddings_est": 596695692.2565918,
    "avg_doclen_est": 67.485595703125
}

Any ideas why the code is getting stuck?

**Comment by okhat** [comment]
I'm guessing you're running out of memory and one of the processes gets killed. How much system (CPU) RAM do you have? How much GPU RAM do you have?

**Comment by susavlsh10** [comment]
The CPU RAM is 48 GB and the GPU has 8 GB. How much memory does the indexing script require for ColBERTv2? Furthermore, could a single GPU be used for indexing or does the script only support multi-GPU systems?

**Comment by lboesen** [comment]
Hi I am having same issues on the ColBERT:

Available RAM : 40.000 GB
CPU count: 8
CPU model: AMD EPYC 7413 24-Core Processor
GPU count: 2
GPU model: 2 x NVIDIA A40


nranks = 1 	 num_gpus = 2 	 device=0
{
    "ncells": null,
    "centroid_score_threshold": null,
    "ndocs": null,
    "index_path": null,
    "nbits": 2,
    "kmeans_niters": 4,
    "resume": false,
    "similarity": "cosine",
    "bsize": 64,
    "accumsteps": 1,
    "lr": 3e-6,
    "maxsteps": 500000,
    "save_every": null,
    "warmup": null,
    "warmup_bert": null,
    "relu": false,
    "nway": 2,
    "use_ib_negatives": false,
    "reranker": false,
    "distillation_alpha": 1.0,
    "ignore_scores": false,
    "query_maxlen": 32,
    "attend_to_mask_tokens": false,
    "interaction": "colbert",
    "dim": 128,
    "doc_maxlen": 220,
    "mask_punctuation": true,
    "checkpoint": "\/home\/model_runs\/colBERT\/",
    "triples": null,
    "collection": "\/home\/data\/collection.tsv",
    "queries": null,
    "index_name": "msmarco.nbits=2",
    "overwrite": true,
    "root": "\/home\/experiments",
    "experiment": "default",
    "index_root": null,
    "name": "2022-11\/19\/07.53.46",
    "rank": 0,
    "nranks": 1,
    "amp": true,
    "gpus": 2
}

**Comment by okhat** [comment]
@susavlsh10 One GPU is fine. I think you and @lboesen are probably running out of (system CPU) memory.

When you index a smaller collection, does it work? e.g., does the default collection in the Jupyter notebook work for you?

**Comment by okhat** [comment]
Any updates here? I'll close otherwise

**Comment by Ajaypawar02** [comment]
I am also having the same issue .
 I am running this repo on google colab. 
Any suggestion regarding this ?

**Comment by ishaan16** [comment]
I am facing the same issue. This is related to faiss k means training. I found that the issue occurs on this [line](https://github.com/stanford-futuredata/ColBERT/blob/43ae55077c5c793d382b7ee3ed6b57630bbcd22e/colbert/indexing/collection_indexer.py#L484)
and am trying to find out why is that failing. Earlier I faced several issues while installing faiss and so this was natural that it leads to an issue. It would be good if you can mention which version of faiss-cpu works with colbert

**Comment by sgowdaks** [comment]
Hi, I am having the same problem, My indexer process gets stuck.

I monitored processes in `htop`, and this is what I see while the processes are stuck:
 
<img width="1114" alt="Screenshot 2023-06-07 195703" src="https://github.com/stanford-futuredata/ColBERT/assets/56445524/4be4413d-1e2d-4cc8-9f1e-20d313cf8f8f">

After interrupting(CTRL+C) it, here is the stacktrace I get:
```python 
Traceback (most recent call last):
  File "colbert_index.py", line 75, in <module>
    indexer.index(
  File "/mnt/e/sg/ColBERT/colbert/indexer.py", line 74, in index
    self.__launch(collection)
  File "/mnt/e/sg/ColBERT/colbert/indexer.py", line 85, in __launch
    launcher.launch(self.config, collection, shared_lists, shared_queues)
  File "/mnt/e/sg/ColBERT/colbert/infra/launcher.py", line 76, in launch
    return_values = sorted([return_value_queue.get() for _ in all_procs])
  File "/mnt/e/sg/ColBERT/colbert/infra/launcher.py", line 76, in <listcomp>
    return_values = sorted([return_value_queue.get() for _ in all_procs])
  File "/home/sg/miniconda3/envs/colbert/lib/python3.8/multiprocessing/queues.py", line 97, in get
    res = self._recv_bytes()
  File "/home/sg/miniconda3/envs/colbert/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/sg/miniconda3/envs/colbert/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/sg/miniconda3/envs/colbert/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
/home/sg/miniconda3/envs/colbert/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

 The point in code where it gets frozen (on my dataset) is here:
https://github.com/stanford-futuredata/ColBERT/blob/83658dcab6b48ec089c186508355b55efb6e2ba8/colbert/infra/launcher.py#L76-L77
 
 Please help! Thanks in advance.

**Comment by eggie5** [comment]
same w/ only two docs

```
[Jul 05, 21:00:36] #> Creating directory /content/experiments/default/indexes/asdf 


#> Starting...
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
[<ipython-input-11-c80098a4da4c>](https://localhost:8080/#) in <cell line: 1>()
----> 1 indexer.index(name="asdf", collection=["asdf", "fdsa"])

7 frames
[/usr/lib/python3.10/multiprocessing/connection.py](https://localhost:8080/#) in _recv(self, size, read)
    377         remaining = size
    378         while remaining > 0:
--> 379             chunk = read(handle, remaining)
    380             n = len(chunk)
    381             if n == 0:

KeyboardInterrupt:
```

**Comment by okhat** [comment]
Folks who are still facing issues can use this free Google Colab: https://colab.research.google.com/github/stanford-futuredata/ColBERT/blob/main/docs/intro2new.ipynb

**Comment by eggie5** [comment]
My issue is from this notebook on colab

On July 5, 2023, GitHut ***@***.***> wrote:
> Folks who are still facing issues can use this free Google Colab:
> <https://colab.research.google.com/github/stanford-
> futuredata/ColBERT/blob/main/docs/intro2new.ipynb>
>

—
Reply to this email directly, view it on GitHub
<https://github.com/stanford-futuredata/ColBERT/issues/139#issuecomment-
1622559139>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAAIYWJ7YOZMTWSRVXBVL3XOXM55ANCNFSM6AAAAAARWZRV3U>.
You are receiving this because you commented.Message ID: <stanford-
***@***.***>

**Comment by okhat** [comment]
I just ran it now and it works for me, on Colab. Did you make sure to choose a GPU?

**Comment by okhat** [comment]
Also please don't try to index 2 documents. Indexing is meant for at least a few hundred documents. It may take 10-15 minutes.

**Comment by anhvth** [comment]
I try on two computers same enviroments, one can run as expected after sometime
The other wait forver in this loop
```bash
    ],
    "queries": null,
    "index_name": "lifestyle.dev.2bits",
    "overwrite": false,
    "root": "\/mnt\/nfs-data\/users\/anhvth5\/projects\/ColBERT\/experiments",
    "experiment": "notebook_debug",
    "index_root": null,
    "name": "2023-11\/09\/06.10.24",
    "rank": 0,
    "nranks": 1,
    "amp": true,
    "gpus": 8
}
[Nov 09, 06:33:16] [0]           # of sampled PIDs = 10          sampled_pids[:3] = [6, 0, 4]
[Nov 09, 06:33:16] [0]           #> Encoding 10 passages..
[Nov 09, 06:38:04] [0]           avg_doclen_est = 165.6999969482422      len(local_sample) = 10
[Nov 09, 06:38:04] [0]           Creaing 512 partitions.
[Nov 09, 06:38:04] [0]           *Estimated* 1,656 embeddings.
[Nov 09, 06:38:04] [0]           #> Saving the indexing plan to /mnt/nfs-data/users/anhvth5/projects/ColBERT/experiments/notebook_debug/indexes/lifestyle.dev.2bits/plan.json ..



^CTraceback (most recent call last):
  File "scripts/index_test.py", line 63, in <module>
    main()
  File "scripts/index_test.py", line 56, in main
    indexer.index(name=index_name, collection=collection, overwrite=True)
  File "/mnt/nfs-data/users/anhvth5/projects/ColBERT/colbert/indexer.py", line 74, in index
    self.__launch(collection)
  File "/mnt/nfs-data/users/anhvth5/projects/ColBERT/colbert/indexer.py", line 85, in __launch
    launcher.launch(self.config, collection, shared_lists, shared_queues)
  File "/mnt/nfs-data/users/anhvth5/projects/ColBERT/colbert/infra/launcher.py", line 76, in launch
    return_values = sorted([return_value_queue.get() for _ in all_procs])
  File "/mnt/nfs-data/users/anhvth5/projects/ColBERT/colbert/infra/launcher.py", line 76, in <listcomp>
    return_values = sorted([return_value_queue.get() for _ in all_procs])
  File "/home/ubuntu/miniconda3/envs/colbert/lib/python3.8/multiprocessing/queues.py", line 97, in get
    res = self._recv_bytes()
  File "/home/ubuntu/miniconda3/envs/colbert/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/ubuntu/miniconda3/envs/colbert/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/ubuntu/miniconda3/envs/colbert/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
```

**Comment by deter3** [comment]
I have the same problem , code stocked in "Saving the indexing plan to /workspace/experiments/notebook/indexes/lifestyle.dev.2bits/plan.json" without any progress . I tried uninstall faiss-gpu and install faiss-cpu . it's working but too slow .

**Comment by anhvth** [comment]
remove ~/.cache/torch_ext might help

**Comment by deter3** [comment]
> Removing and re-creating the conda environment made it work

Same here . The code stuck at the same place(Saving the indexing plan to..........) and using conda to create the environment and python setup.py install had no problem on faiss-gpu .

**Comment by pauliustumas** [comment]
> remove ~/.cache/torch_ext might help

Exactly right. I was using venv, deleting everything ~/.cache/torch_extensions resolved the issue

**Comment by jmugan** [comment]
Same problem here in Google colab trying to index a few documents.

**Comment by xmanners** [comment]
I  also encountered the same problem, and I FINALLY solve it by creating envrion first (by cpu_.yml conifg), run setup.py build & install, and finally works!
![success](https://github.com/user-attachments/assets/3f10c27b-a3c4-468b-bf3a-030dc1126c60)
So here's my solution:
1. conda env create -r [conda_env_cpu.yml](https://github.com/stanford-futuredata/ColBERT/blob/main/conda_env_cpu.yml)
2. conda activate colbert
3. python [setup.py](https://github.com/stanford-futuredata/ColBERT/blob/main/setup.py) build
4. python [setup.py](https://github.com/stanford-futuredata/ColBERT/blob/main/setup.py) install
5. python [setup.py](https://github.com/stanford-futuredata/ColBERT/blob/main/setup.py) clean
then it solved :)
