### ISSUE TITLE
colbert.train FAILED: running distributed training

### ISSUE THREAD

**Issue by liudan111** [stanford-futuredata/ColBERT#213]
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
colbert.train FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-06-13_12:25:13
  host      : tu-c0r1n00.bullx
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 182503)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-13_12:25:13
  host      : tu-c0r1n00.bullx
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 182502)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by okhat** [comment]
Hmm do you have the traceback? This isn't enough info to help understand what went wrong unfortunately

**Comment by okhat** [comment]
@liudan111 I don't think we support multi-node unfortunately. Also, with batch size 32 you won't benefit from having 8 GPUs anyway. Four GPUs will be very fast!

**Comment by liudan111** [comment]
> @liudan111 I don't think we support multi-node unfortunately. Also, with batch size 32 you won't benefit from having 8 GPUs anyway. Four GPUs will be very fast!

Thanks for your reply,  so for multi-nodes and GPUs, I should set  batch size larger to use all nodes and gpus?

**Comment by okhat** [comment]
Batch size 32 is fine. But please just use one node, with 4 gpus. That will work well

**Comment by liudan111** [comment]
> Batch size 32 is fine. But please just use one node, with 4 gpus. That will work well

That's great, I am wondering if I can adapt it to multi-nodes, as I have a quite large data, training is so slow on one node.

**Comment by okhat** [comment]
Hmm how large is the data? I’ve never seen a meaningful benefit from training on more than 10M triples. With 4 gpus, you can train on this many in a couple of days, so it’s pretty fast.

We don’t support multi-node training unfortunately

**Comment by liudan111** [comment]
UDA_VISIBLE_DEVICES="0,1" python -m torch.distributed.launch --nproc_per_node=2 -m colbert.train --amp --query_maxlen 128 --doc_maxlen 256 --mask-punctuation --bsize 32 --accum 1 --triples Data/triples.train.intact.tsv --root model/colesm_cosine_hh --experiment psg --similarity cosine

Error: 
/home/dp289/dp289/dc-liu5/anaconda3/envs/PPI/lib/python3.9/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
usage: train.py [-h] [--root ROOT] [--experiment EXPERIMENT] [--run RUN] [--local_rank RANK] [--similarity {cosine,l2}] [--dim DIM] [--query_maxlen QUERY_MAXLEN]
                [--doc_maxlen DOC_MAXLEN] [--mask-punctuation] [--resume] [--resume_optimizer] [--checkpoint CHECKPOINT] [--lr LR] [--maxsteps MAXSTEPS] [--bsize BSIZE]
                [--accum ACCUMSTEPS] [--amp] [--base_model BASE_MODEL] --triples TRIPLES [--queries QUERIES] [--collection COLLECTION]
usage: train.py [-h] [--root ROOT] [--experiment EXPERIMENT] [--run RUN] [--local_rank RANK] [--similarity {cosine,l2}] [--dim DIM] [--query_maxlen QUERY_MAXLEN]
                [--doc_maxlen DOC_MAXLEN] [--mask-punctuation] [--resume] [--resume_optimizer] [--checkpoint CHECKPOINT] [--lr LR] [--maxsteps MAXSTEPS] [--bsize BSIZE]
                [--accum ACCUMSTEPS] [--amp] [--base_model BASE_MODEL] --triples TRIPLES [--queries QUERIES] [--collection COLLECTION]
train.py: error: unrecognized arguments: --local-rank=0
train.py: error: unrecognized arguments: --local-rank=1
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 119459) of binary: /home/dp289/dp289/dc-liu5/anaconda3/envs/PPI/bin/python
Traceback (most recent call last):
  File "/home/dp289/dp289/dc-liu5/anaconda3/envs/PPI/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dc-liu5/anaconda3/envs/PPI/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dc-liu5/anaconda3/envs/PPI/lib/python3.9/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/dc-liu5/anaconda3/envs/PPI/lib/python3.9/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/dc-liu5/anaconda3/envs/PPI/lib/python3.9/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/dc-liu5/anaconda3/envs/PPI/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/dc-liu5/anaconda3/envs/PPI/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/dc-liu5/anaconda3/envs/PPI/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
colbert.train FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-06-30_17:02:17
  host      : tu-c0r3n18.bullx
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 119460)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-30_17:02:17
  host      : tu-c0r3n18.bullx
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 119459)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
