### ISSUE TITLE
ImportError: .../torch_extensions/py38_cu117/decompress_residuals_cpp/decompress_residuals_cpp.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wiany11** [stanford-futuredata/ColBERT#356]
After 
```
conda env create -f conda_env[_cpu].yml
conda activate colbert
```
I faced two problems

- `Error "ImportError: cannot import name 'packaging' from 'pkg_resources'" when using latest setuptools version...`
  - Solution: https://github.com/aws-neuron/aws-neuron-sdk/issues/893
- `subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status`
  - Solution: https://github.com/pytorch/vision/issues/2360

And then I faced the following problem. How can I solve it?

```
(colbert) jovyan@colbert-240712-1756-0:~/ColBERT$ python index.py


[Jul 15, 05:46:49] #> Note: Output directory /home/jovyan/ColBERT/experiments/msmarco/indexes/msmarco.nbits=2 already exists


[Jul 15, 05:46:49] #> Will delete 1 files already at /home/jovyan/ColBERT/experiments/msmarco/indexes/msmarco.nbits=2 in 20 seconds...
#> Starting...
nranks = 1       num_gpus = 1    device=0
{
    "query_token_id": "[unused0]",
    "doc_token_id": "[unused1]",
    "query_token": "[Q]",
    "doc_token": "[D]",
    "ncells": null,
    "centroid_score_threshold": null,
    "ndocs": null,
    "load_index_with_mmap": false,
    "index_path": null,
    "index_bsize": 64,
    "nbits": 2,
    "kmeans_niters": 20,
    "resume": false,
    "pool_factor": 1,
    "clustering_mode": "hierarchical",
    "protected_tokens": 0,
    "similarity": "cosine",
    "bsize": 64,
    "accumsteps": 1,
    "lr": 1e-5,
    "maxsteps": 400000,
    "save_every": null,
    "warmup": 20000,
    "warmup_bert": null,
    "relu": false,
    "nway": 64,
    "use_ib_negatives": true,
    "reranker": false,
    "distillation_alpha": 1.0,
    "ignore_scores": false,
    "model_name": null,
    "query_maxlen": 32,
    "attend_to_mask_tokens": false,
    "interaction": "colbert",
    "dim": 128,
    "doc_maxlen": 180,
    "mask_punctuation": true,
    "checkpoint": "\/home\/jovyan\/ColBERT\/data\/colbertv2.0",
    "triples": "\/future\/u\/okhattab\/root\/unit\/experiments\/2021.10\/downstream.distillation.round2.2_score\/round2.nway6.cosine.ib\/examples.64.json",
    "collection": "\/home\/jovyan\/ColBERT\/data\/collection.tsv",
    "queries": "\/future\/u\/okhattab\/data\/MSMARCO\/queries.train.tsv",
    "index_name": "msmarco.nbits=2",
    "overwrite": false,
    "root": "\/home\/jovyan\/ColBERT\/experiments",
    "experiment": "msmarco",
    "index_root": null,
    "name": "2024-07\/15\/05.46.47",
    "rank": 0,
    "nranks": 1,
    "amp": true,
    "gpus": 1,
    "avoid_fork_if_possible": false
}
[Jul 15, 05:47:14] #> Loading collection...
0M 1M 2M 3M 4M 5M 6M 7M 8M 
[Jul 15, 05:47:38] [0]           # of sampled PIDs = 521173      sampled_pids[:3] = [6989721, 170610, 5010345]
[Jul 15, 05:47:42] [0]           #> Encoding 521173 passages..
[Jul 15, 06:40:09] [0]           avg_doclen_est = 67.485595703125        len(local_sample) = 521,173
[Jul 15, 06:40:23] [0]           Creating 262,144 partitions.
[Jul 15, 06:40:23] [0]           *Estimated* 596,695,692 embeddings.
[Jul 15, 06:40:23] [0]           #> Saving the indexing plan to /home/jovyan/ColBERT/experiments/msmarco/indexes/msmarco.nbits=2/plan.json ..
Clustering 35121672 points in 128D to 262144 clusters, redo 1 times, 20 iterations
  Preprocessing in 4.08 s
  Iteration 19 (8763.36 s, search 8406.39 s): objective=8.38989e+06 imbalance=1.248 nsplit=0              
[Jul 15, 09:07:04] Loading decompress_residuals_cpp extension (set COLBERT_LOAD_TORCH_EXTENSION_VERBOSE=True for more info)...
Process Process-2:
Traceback (most recent call last):
  File "/home/jovyan/.conda/envs/colbert/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/jovyan/.conda/envs/colbert/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jovyan/ColBERT/colbert/infra/launcher.py", line 134, in setup_new_process
    return_val = callee(config, *args)
  File "/home/jovyan/ColBERT/colbert/indexing/collection_indexer.py", line 33, in encode
    encoder.run(shared_lists)
  File "/home/jovyan/ColBERT/colbert/indexing/collection_indexer.py", line 68, in run
    self.train(shared_lists) # Trains centroids from selected passages
  File "/home/jovyan/ColBERT/colbert/indexing/collection_indexer.py", line 237, in train
    bucket_cutoffs, bucket_weights, avg_residual = self._compute_avg_residual(centroids, heldout)
  File "/home/jovyan/ColBERT/colbert/indexing/collection_indexer.py", line 315, in _compute_avg_residual
    compressor = ResidualCodec(config=self.config, centroids=centroids, avg_residual=None)
  File "/home/jovyan/ColBERT/colbert/indexing/codecs/residual.py", line 24, in __init__
    ResidualCodec.try_load_torch_extensions(self.use_gpu)
  File "/home/jovyan/ColBERT/colbert/indexing/codecs/residual.py", line 103, in try_load_torch_extensions
    decompress_residuals_cpp = load(
  File "/home/jovyan/.conda/envs/colbert/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/jovyan/.conda/envs/colbert/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1534, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/jovyan/.conda/envs/colbert/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1936, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/jovyan/.cache/torch_extensions/py38_cu117/decompress_residuals_cpp/decompress_residuals_cpp.so: cannot open shared object file: No such file or directory
```

**Comment by pverma3** [comment]
Hi @wiany11 , how did you solve it? I am also getting same error.

**Comment by wiany11** [comment]
@pverma3 
Kinda... I just used their Docker image. It somewhat worked...

**Comment by robinnarsinghranabhat** [comment]
I was getting similar issues. This installation procedure worked

```
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b
source ~/miniconda3/bin/activate
conda init

git clone https://github.com/stanford-futuredata/ColBERT.git
cd ColBERT
conda env create -f conda_env.yml
conda activate colbert
pip install -e .

## At this point, I was getting ImportError from torch. So, had to do this : 
conda remove -y --force pytorch torchvision torchaudio cudatoolkit
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

## Then was getting missing header file `crypt.h` problem as some custom C++ extensions were being compiled. This fixed it : 
# this will add that missing `crypt.h` header file, required to compile that those extension
conda install -c conda-forge libxcrypt
export CPATH="$CONDA_PREFIX/include:$CPATH"

## Finally, got issue saying, can't compile. Turns out compiler path wasn't pointing to ones inside conda environment
echo $PATH
which nvcc
which g++
which c++

# Set the compiler environment variables to use your colbert environment
export CC="$CONDA_PREFIX/bin/gcc"
export CXX="$CONDA_PREFIX/bin/g++"
export CUDA_HOST_COMPILER="$CONDA_PREFIX/bin/g++"
```

## Code to test ( [from this discussion](https://github.com/stanford-futuredata/ColBERT/issues/371#issuecomment-3251906773) )
```
# quickstart_index.py

import colbert
from colbert import Indexer, Searcher
from colbert.infra import Run, RunConfig, ColBERTConfig
from colbert.data import Queries, Collection
from datasets import load_dataset

def main():
    nbits = 2  
    ndocs = 10_000
    dataset_name = "Genomics"
    index_name = f'{dataset_name}.{nbits}bits'

    passages = load_dataset("UKPLab/dapr", f"{dataset_name}-corpus", split="test")

    checkpoint = 'colbert-ir/colbertv2.0'

    with Run().context(RunConfig(nranks=1, experiment='notebook')):
        config = ColBERTConfig(doc_maxlen=300, nbits=nbits, kmeans_niters=4)
        indexer = Indexer(checkpoint=checkpoint, config=config)
        indexer.index(name=index_name, collection=passages[:100]["text"], overwrite=True)

if __name__ == '__main__':
    main()

# quickstart_search.py

from colbert.infra import Run, RunConfig, ColBERTConfig
from colbert import Searcher

if __name__=='__main__':
    with Run().context(RunConfig(nranks=1, experiment="notebook")):

        config = ColBERTConfig(
            root="/notebooks/ColBERT/experiments",
        )
        searcher = Searcher(index="Genomics.2bits", config=config)
        query = "What is a disease?"
        ranking = searcher.search(query, k=10)
        print(ranking)
```
