### ISSUE TITLE
Use ColBERT on Google Colab with a specific Dataset

### ISSUE THREAD

**Issue by poorya2021** [stanford-futuredata/ColBERT#76]
Hi Omar
Thank you for your great code
I was trying to train Colbert with a specific dataset on Google Colab, but I could not use that script you provided.
When I used the "torch.distributed.launch" I got the warning "torch.distributed.launch is deprecated" so I used "torch.distributed.run"  instead of "torch.distributed.launch" .
I tried several different commands but did not succeed and encountered the following error:

"Error while finding module specification for 'colbert.train' (ModuleNotFoundError: No module named 'colbert')"

1)
`! CUDA_VISIBLE_DEVICES="0" \
        python -m torch.distributed.run --nproc_per_node=1 -m colbert.train \
        --amp --doc_maxlen 180 --mask-punctuation --bsize 32 --accum 1 \
        --queries content/drive/My\ Drive/Colab\ Notebooks/Sajad_DataSet/ColBERT_DS/tsv\ files/colbert_train_questions_pos.tsv \
        --collection content/drive/My\ Drive/Colab\ Notebooks/Sajad_DataSet/ColBERT_DS/tsv\ files/cobert_full_collection.tsv`

Error:

 `/usr/bin/python3: Error while finding module specification for 'colbert.train' (ModuleNotFoundError: No module named 'colbert')
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1035) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 723, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
colbert.train FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2021-11-19_15:44:24
  host      : 88a50f7ecce5
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1035)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html 
==========================================================`

I tried to put the whole Colbert package in my Google Drive and used the link in the following command, but to no avail.

2)

`! CUDA_VISIBLE_DEVICES="0" \
        python -m torch.distributed.run --nproc_per_node=1 -m /content/drive/My\ Drive/Colab\ Notebooks/ColBERT-master/colbert.train \
        --amp --doc_maxlen 180 --mask-punctuation --bsize 32 --accum 1 \
        --queries content/drive/My\ Drive/Colab\ Notebooks/Sajad_DataSet/ColBERT_DS/tsv\ files/colbert_train_questions_pos.tsv \
        --collection content/drive/My\ Drive/Colab\ Notebooks/Sajad_DataSet/ColBERT_DS/tsv\ files/cobert_full_collection.tsv`

Error:

`/usr/bin/python3: Error while finding module specification for '/content/drive/My Drive/Colab Notebooks/ColBERT-master/colbert.train' (ModuleNotFoundError: No module named '/content/drive/My Drive/Colab Notebooks/ColBERT-master/colbert')
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 163) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 723, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/content/drive/My Drive/Colab Notebooks/ColBERT-master/colbert.train FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2021-11-19_17:28:21
  host      : 6b26d0da6c66
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 163)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================`

3)

`!python -m torch.distributed.run --nproc_per_node=1 \
        -m /content/drive/My\ Drive/Colab\ Notebooks/ColBERT-master/colbert.train --amp --doc_maxlen 180 --mask-punctuation --bsize 32 --accum 1 \
        --triples /content/drive/My\ Drive/Colab\ Notebooks/Sajad_DataSet/ColBERT_DS/tsv\ files/colbert_train_questions_pos.tsv \
        --root /content/drive/My\ Drive/Colab\ Notebooks/Sajad_DataSet/ColBERT_DS/tsv\ files/cobert_full_collection.tsv`

Error:

`/usr/bin/python3: Error while finding module specification for '/content/drive/My Drive/Colab Notebooks/ColBERT-master/colbert.train' (ModuleNotFoundError: No module named '/content/drive/My Drive/Colab Notebooks/ColBERT-master/colbert')
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1147) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 723, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/content/drive/My Drive/Colab Notebooks/ColBERT-master/colbert.train FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2021-11-19_15:51:54
  host      : 88a50f7ecce5
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1147)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================`

I hope you can help me
Thank you

**Comment by okhat** [comment]
Hi @poorya2021 ! If you want to use Google Colab, I suggest you check out pyterrier-colbert, which has built-in examples with ColBERT on Colab.

https://github.com/terrierteam/pyterrier_colbert

**Comment by okhat** [comment]
Let me know if you face any other issues.
