### ISSUE TITLE
Error when run ColBERTv2 intro code in a python script

### ISSUE THREAD

**Issue by jordane95** [stanford-futuredata/ColBERT#93]
Hi,
I tried your [notebook](https://github.com/stanford-futuredata/ColBERT/blob/new_api/docs/intro.ipynb) code illustrating the usage of ColBERTv2's API. It works fine.
But I want to run it directly on a linux server in a python file. So I copy the code to a python script `intro.py` and try to execute it. But the script raises an EOF error regarding the `multiprocessing` lib when executing the line
```Python
indexer.index(name=index_name, collection=collection, overwrite=True)
```
Could you please help me fix it?

More details of the error are
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lzh/code/ColBERTv2/docs/intro.py", line 31, in <module>
    indexer.index(name=index_name, collection=collection, overwrite=True)
  File "../colbert/indexer.py", line 74, in index
    self.__launch(collection)
  File "../colbert/indexer.py", line 79, in __launch
    manager = mp.Manager()
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/context.py", line 56, in Manager
    m.start()
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/managers.py", line 563, in start
    self._process.start()
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "intro.py", line 31, in <module>
    indexer.index(name=index_name, collection=collection, overwrite=True)
  File "../colbert/indexer.py", line 74, in index
    self.__launch(collection)
  File "../colbert/indexer.py", line 79, in __launch
    manager = mp.Manager()
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/context.py", line 56, in Manager
    m.start()
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/managers.py", line 567, in start
    self._address = reader.recv()
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/anaconda/envs/colbert-v0.4/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by okhat** [comment]
Yes! Please wrap your code in:

```
import etc..

if __name__ == '__main__':
    # your code here

```

**Comment by jordane95** [comment]
That helps! Thank you so much!!!
